[package]
name = "cep18-test-contract"
version = "1.0.0"
authors = ["MichaÅ‚ Papierski <michal@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "cep18_test_contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
casper-contract = "2.0.0"
casper-types = "2.0.0"
