[package]
name = "erc20-tests"
version = "0.1.0"
authors = ["MichaÅ‚ Papierski <michal@casperlabs.io>"]
edition = "2018"

[dev-dependencies]
base64 = "0.13.0"
blake2 = "0.9.2"
casper-engine-test-support = { version = "1.3.2", features = ["test-support"] }
casper-erc20 = { version = "0.2.0", features = ["std"], path = "../../erc20" }
casper-types = { version = "1.3.2", features = ["std"] }
hex = "0.4.3"

[[bin]]
name = "erc20-tests"
path = "src/integration_tests.rs"
bench = false
doctest = false
